### ISSUE TITLE
Getting 401 Unauthorized but not still prompted to sign in

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Chrome-Extension#28]
Getting 
Remote Address:104.45.222.13:443
Request URL:https://quantimo.do/api/variables
Request Method:GET
Status Code:401 Unauthorized

Normally, the signin dialog should pop up if I'm not logged in at quantimo.do.

**Comment by pankajr03** [comment]
Hello Mike,

How are you?
It's quite long we have not communicated.
Is everything fine.
Any work for me.


On Tue, Apr 14, 2015 at 2:44 AM, Mike P. Sinn <notifications@github.com>
wrote:

> Getting
> Remote Address:104.45.222.13:443
> Request URL:https://quantimo.do/api/variables
> Request Method:GET
> Status Code:401 Unauthorized
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abolitionist-Project/QuantiModo-Chrome-Extension/issues/28>
> .
>



-- 
Regards,
Pankaj
