### ISSUE TITLE
Move libraries to /libs folder

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Chrome-Extension#31]

**Comment by pankajr03** [comment]
Could you please elaborate it more in details, as i did not able to find it in extension folders.

**Comment by mikepsinn** [comment]
Hi!  It was easier to do than explain: https://github.com/Abolitionist-Project/QuantiModo-Chrome-Extension/commit/037b00a5c24a48efc1900d1dbbf784d0c6c06bb0
